blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/skarllot/SourceGenerators#guide
    about: Read our documentation.
  - name: â­ Sponsor Raiqub T4 Code Writer
    url: https://github.com/sponsors/skarllot
    about: Help the continued development.
  - name: ğŸ’¬ Ask on Github Discussions
    url: https://github.com/skarllot/SourceGenerators/discussions
    about: The best place for asking general purpose questions.
